server:
  servlet:
    context-path: /examsys

mybatis:
  type-aliases-package: com.damo.examsys.entity
  mapper-locations: classpath:mapper/*.xml

  #下划线转驼峰
  configuration:
    map-underscore-to-camel-case: true



spring:

  # redis数据库服务器id 端口号 密码
  redis:
    host: 47.96.142.78
    port: 6379

    #默认不会启用连接池：
    #连接池配置:
    lettuce:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8

  #数据库连接池:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.96.142.78:3306/examsys?useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 2579
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

#thymeleaf日志信息
logging:
  level:
    org:
      thymeleaf: info

#pagehelper配置信息
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql